version: "3.8"

name: "skillex"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT_HOST:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_HOST:-5555}:${APP_PORT:-3000}"
      - "${APP_PORT_DEBUG_HOST:-9333}:${APP_PORT_DEBUG:-9229}"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - mysql
